<?php

declare(strict_types=1);

namespace IBroStudio\DataObjects\Enums;

enum CurrencyEnum: string
{
    case AED = 'United Arab Emirates dirham';
    case AFN = 'Afghan afghani';
    case ALL = 'Albanian lek';
    case AMD = 'Armenian dram';
    case ANG = 'Netherlands Antillean guilder';
    case AOA = 'Angolan kwanza';
    case ARS = 'Argentine peso';
    case AUD = 'Australian dollar';
    case AWG = 'Aruban florin';
    case AZN = 'Azerbaijani manat';
    case BAM = 'Bosnia and Herzegovina convertible mark';
    case BBD = 'Barbados dollar';
    case BDT = 'Bangladeshi taka';
    case BGN = 'Bulgarian lev';
    case BHD = 'Bahraini dinar';
    case BIF = 'Burundian franc';
    case BMD = 'Bermudian dollar';
    case BND = 'Brunei dollar';
    case BOB = 'Boliviano';
    case BOV = 'Bolivian Mvdol (funds code)';
    case BRL = 'Brazilian real';
    case BSD = 'Bahamian dollar';
    case BTC = 'Bitcoin';
    case BTN = 'Bhutanese ngultrum';
    case BWP = 'Botswana pula';
    case BYR = 'Belarusian ruble';
    case BZD = 'Belize dollar';
    case CAD = 'Canadian dollar';
    case CDF = 'Congolese franc';
    case CHE = 'WIR Euro (complementary currency)';
    case CHF = 'Swiss franc';
    case CHW = 'WIR Franc (complementary currency)';
    case CLF = 'Unidad de Fomento (funds code)';
    case CLP = 'Chilean peso';
    case CNY = 'Chinese yuan';
    case COP = 'Colombian peso';
    case COU = 'Unidad de Valor Real';
    case CRC = 'Costa Rican colon';
    case CUP = 'Cuban peso';
    case CVE = 'Cape Verde escudo';
    case CZK = 'Czech koruna';
    case DJF = 'Djiboutian franc';
    case DKK = 'Danish krone';
    case DOP = 'Dominican peso';
    case DZD = 'Algerian dinar';
    case EGP = 'Egyptian pound';
    case ERN = 'Eritrean nakfa';
    case ETB = 'Ethiopian birr';
    case EUR = 'Euro';
    case FJD = 'Fiji dollar';
    case FKP = 'Falkland Islands pound';
    case GBP = 'Pound sterling';
    case GEL = 'Georgian lari';
    case GHS = 'Ghanaian cedi';
    case GIP = 'Gibraltar pound';
    case GMD = 'Gambian dalasi';
    case GNF = 'Guinean franc';
    case GTQ = 'Guatemalan quetzal';
    case GYD = 'Guyanese dollar';
    case HKD = 'Hong Kong dollar';
    case HNL = 'Honduran lempira';
    case HTG = 'Haitian gourde';
    case HUF = 'Hungarian forint';
    case IDR = 'Indonesian rupiah';
    case ILS = 'Israeli new shekel';
    case INR = 'Indian rupee';
    case IQD = 'Iraqi dinar';
    case IRR = 'Iranian rial';
    case ISK = 'Icelandic króna';
    case JMD = 'Jamaican dollar';
    case JOD = 'Jordanian dinar';
    case JPY = 'Japanese yen';
    case KES = 'Kenyan shilling';
    case KGS = 'Kyrgyzstani som';
    case KHR = 'Cambodian riel';
    case KMF = 'Comoro franc';
    case KPW = 'North Korean won';
    case KRW = 'South Korean won';
    case KWD = 'Kuwaiti dinar';
    case KYD = 'Cayman Islands dollar';
    case KZT = 'Kazakhstani tenge';
    case LAK = 'Lao kip';
    case LBP = 'Lebanese pound';
    case LKR = 'Sri Lankan rupee';
    case LRD = 'Liberian dollar';
    case LSL = 'Lesotho loti';
    case LYD = 'Libyan dinar';
    case MAD = 'Moroccan dirham';
    case MDL = 'Moldovan leu';
    case MGA = 'Malagasy ariary';
    case MKD = 'Macedonian denar';
    case MMK = 'Myanma kyat';
    case MNT = 'Mongolian tugrik';
    case MOP = 'Macanese pataca';
    case MRU = 'Mauritanian ouguiya';
    case MUR = 'Mauritian rupee';
    case MVR = 'Maldivian rufiyaa';
    case MWK = 'Malawian kwacha';
    case MXN = 'Mexican peso';
    case MXV = 'Mexican Unidad de Inversion (UDI) (funds code)';
    case MYR = 'Malaysian ringgit';
    case MZN = 'Mozambican metical';
    case NAD = 'Namibian dollar';
    case NGN = 'Nigerian naira';
    case NIO = 'Nicaraguan córdoba';
    case NOK = 'Norwegian krone';
    case NPR = 'Nepalese rupee';
    case NZD = 'New Zealand dollar';
    case OMR = 'Omani rial';
    case PAB = 'Panamanian balboa';
    case PEN = 'Peruvian nuevo sol';
    case PGK = 'Papua New Guinean kina';
    case PHP = 'Philippine peso';
    case PKR = 'Pakistani rupee';
    case PLN = 'Polish złoty';
    case PYG = 'Paraguayan guaraní';
    case QAR = 'Qatari riyal';
    case RON = 'Romanian new leu';
    case RSD = 'Serbian dinar';
    case RUB = 'Russian rouble';
    case RWF = 'Rwandan franc';
    case SAR = 'Saudi riyal';
    case SBD = 'Solomon Islands dollar';
    case SCR = 'Seychelles rupee';
    case SDG = 'Sudanese pound';
    case SEK = 'Swedish krona/kronor';
    case SGD = 'Singapore dollar';
    case SHP = 'Saint Helena pound';
    case SLE = 'Sierra Leonean leone';
    case SOS = 'Somali shilling';
    case SRD = 'Surinamese dollar';
    case SSP = 'South Sudanese pound';
    case STN = 'São Tomé and Príncipe dobra';
    case SVC = 'Salvadoran colón';
    case SYP = 'Syrian pound';
    case SZL = 'Swazi lilangeni';
    case THB = 'Thai baht';
    case TJS = 'Tajikistani somoni';
    case TMT = 'Turkmenistani manat';
    case TND = 'Tunisian dinar';
    case TOP = 'Tongan paʻanga';
    case TRY = 'Turkish lira';
    case TTD = 'Trinidad and Tobago dollar';
    case TWD = 'New Taiwan dollar';
    case TZS = 'Tanzanian shilling';
    case UAH = 'Ukrainian hryvnia';
    case UGX = 'Ugandan shilling';
    case USD = 'United States dollar';
    case UYU = 'Uruguayan peso';
    case UZS = 'Uzbekistan som';
    case VES = 'Venezuelan sovereign bolívar';
    case VND = 'Vietnamese dong';
    case VUV = 'Vanuatu vatu';
    case WST = 'Samoan tala';
    case XAF = 'CFA franc BEAC';
    case XCD = 'East Caribbean dollar';
    case XOF = 'CFA franc BCEAO';
    case XPF = 'CFP franc';
    case YER = 'Yemeni rial';
    case ZAR = 'South African rand';
    case ZMW = 'Zambian kwacha';

    public static function enabled(): array
    {
        return array_values(
            collect(self::cases())
                ->filter(function ($currency) {
                    return in_array($currency->name, config('app.currencies', []));
                })
                ->toArray()
        );
    }

    public function getLabel(): string
    {
        return $this->value;
    }

    public function getAlphaCode(): string
    {
        return $this->name;
    }

    public function getNumericCode(): ?string
    {
        return match ($this) {
            self::AED => '784',
            self::AFN => '971',
            self::ALL => '008',
            self::AMD => '051',
            self::ANG => '532',
            self::AOA => '973',
            self::ARS => '032',
            self::AUD => '036',
            self::AWG => '533',
            self::AZN => '944',
            self::BAM => '977',
            self::BBD => '052',
            self::BDT => '050',
            self::BGN => '975',
            self::BHD => '048',
            self::BIF => '108',
            self::BMD => '060',
            self::BND => '096',
            self::BOB => '068',
            self::BOV => '984',
            self::BRL => '986',
            self::BSD => '044',
            self::BTN => '064',
            self::BWP => '072',
            self::BYR => '933',
            self::BZD => '084',
            self::CAD => '124',
            self::CDF => '976',
            self::CHE => '947',
            self::CHF => '756',
            self::CHW => '948',
            self::CLF => '990',
            self::CLP => '152',
            self::CNY => '156',
            self::COP => '170',
            self::COU => '970',
            self::CRC => '188',
            self::CUP => '192',
            self::CVE => '132',
            self::CZK => '203',
            self::DJF => '262',
            self::DKK => '208',
            self::DOP => '214',
            self::DZD => '012',
            self::EGP => '818',
            self::ERN => '232',
            self::ETB => '230',
            self::EUR => '978',
            self::FJD => '242',
            self::FKP => '238',
            self::GBP => '826',
            self::GEL => '981',
            self::GHS => '936',
            self::GIP => '292',
            self::GMD => '270',
            self::GNF => '324',
            self::GTQ => '320',
            self::GYD => '328',
            self::HKD => '344',
            self::HNL => '340',
            self::HTG => '332',
            self::HUF => '348',
            self::IDR => '360',
            self::ILS => '376',
            self::INR => '356',
            self::IQD => '368',
            self::IRR => '364',
            self::ISK => '352',
            self::JMD => '388',
            self::JOD => '400',
            self::JPY => '392',
            self::KES => '404',
            self::KGS => '417',
            self::KHR => '116',
            self::KMF => '174',
            self::KPW => '408',
            self::KRW => '410',
            self::KWD => '414',
            self::KYD => '136',
            self::KZT => '398',
            self::LAK => '418',
            self::LBP => '422',
            self::LKR => '144',
            self::LRD => '430',
            self::LSL => '426',
            self::LYD => '436',
            self::MAD => '504',
            self::MDL => '498',
            self::MGA => '969',
            self::MKD => '807',
            self::MMK => '104',
            self::MNT => '496',
            self::MOP => '446',
            self::MRU => '929',
            self::MUR => '480',
            self::MVR => '462',
            self::MWK => '454',
            self::MXN => '484',
            self::MXV => '979',
            self::MYR => '458',
            self::MZN => '943',
            self::NAD => '516',
            self::NGN => '566',
            self::NIO => '558',
            self::NOK => '578',
            self::NPR => '524',
            self::NZD => '554',
            self::OMR => '512',
            self::PAB => '590',
            self::PEN => '604',
            self::PGK => '598',
            self::PHP => '608',
            self::PKR => '586',
            self::PLN => '985',
            self::PYG => '600',
            self::QAR => '634',
            self::RON => '946',
            self::RSD => '941',
            self::RUB => '643',
            self::RWF => '646',
            self::SAR => '682',
            self::SBD => '090',
            self::SCR => '690',
            self::SDG => '938',
            self::SEK => '752',
            self::SGD => '702',
            self::SHP => '654',
            self::SLE => '925',
            self::SOS => '706',
            self::SRD => '968',
            self::SSP => '728',
            self::STN => '930',
            self::SVC => '222',
            self::SYP => '760',
            self::SZL => '748',
            self::THB => '764',
            self::TJS => '972',
            self::TMT => '934',
            self::TND => '788',
            self::TOP => '776',
            self::TRY => '949',
            self::TTD => '780',
            self::TWD => '901',
            self::TZS => '834',
            self::UAH => '980',
            self::UGX => '800',
            self::USD => '840',
            self::UYU => '858',
            self::UZS => '860',
            self::VES => '928',
            self::VND => '704',
            self::VUV => '548',
            self::WST => '882',
            self::XAF => '950',
            self::XCD => '951',
            self::XOF => '952',
            self::XPF => '953',
            self::YER => '886',
            self::ZAR => '710',
            self::ZMW => '967',
            default => null,
        };
    }

    public function getSymbol(): string
    {
        return html_entity_decode(match ($this) {
            self::AED => '&#1583;.&#1573;',
            self::AFN => '&#65;&#102;',
            self::ALL => '&#76;&#101;&#107;',
            self::AMD => '&#1423;',
            self::ANG => '&#402;',
            self::AOA => '&#75;&#122;',
            self::ARS => '&#36;',
            self::AUD => '&#36;',
            self::AWG => '&#402;',
            self::AZN => '&#1084;&#1072;&#1085;',
            self::BAM => '&#75;&#77;',
            self::BBD => '&#36;',
            self::BDT => '&#2547;',
            self::BGN => '&#1083;&#1074;',
            self::BHD => '.&#1583;.&#1576;',
            self::BIF => '&#70;&#66;&#117;',
            self::BMD => '&#36;',
            self::BND => '&#36;',
            self::BOB => '&#36;&#98;',
            self::BRL => '&#82;&#36;',
            self::BSD => '&#36;',
            self::BTC => '&#3647;',
            self::BTN => '&#78;&#117;&#46;',
            self::BWP => '&#80;',
            self::BYR => '&#112;&#46;',
            self::BZD => '&#66;&#90;&#36;',
            self::CAD => '&#36;',
            self::CDF => '&#70;&#67;',
            self::CHF => '&#67;&#72;&#70;',
            self::CLF => '',
            self::CLP => '&#36;',
            self::CNY => '&#165;',
            self::COP => '&#36;',
            self::CRC => '&#8353;',
            self::CUP => '&#8396;',
            self::CVE => '&#36;',
            self::CZK => '&#75;&#269;',
            self::DJF => '&#70;&#100;&#106;',
            self::DKK => '&#107;&#114;',
            self::DOP => '&#82;&#68;&#36;',
            self::DZD => '&#1583;&#1580;',
            self::EGP => '&#163;',
            self::ERN => '&#78;&#102;&#107;',
            self::ETB => '&#66;&#114;',
            self::EUR => '&#8364;',
            self::FJD => '&#36;',
            self::FKP => '&#163;',
            self::GBP => '&#163;',
            self::GEL => '&#4314;',
            self::GHS => '&#162;',
            self::GIP => '&#163;',
            self::GMD => '&#68;',
            self::GNF => '&#70;&#71;',
            self::GTQ => '&#81;',
            self::GYD => '&#36;',
            self::HKD => '&#36;',
            self::HNL => '&#76;',
            self::HTG => '&#71;',
            self::HUF => '&#70;&#116;',
            self::IDR => '&#82;&#112;',
            self::ILS => '&#8362;',
            self::INR => '&#8377;',
            self::IQD => '&#1593;.&#1583;',
            self::IRR => '&#65020;',
            self::ISK => '&#107;&#114;',
            self::JMD => '&#74;&#36;',
            self::JOD => '&#74;&#68;',
            self::JPY => '&#165;',
            self::KES => '&#75;&#83;&#104;',
            self::KGS => '&#1083;&#1074;',
            self::KHR => '&#6107;',
            self::KMF => '&#67;&#70;',
            self::KPW => '&#8361;',
            self::KRW => '&#8361;',
            self::KWD => '&#1583;.&#1603;',
            self::KYD => '&#36;',
            self::KZT => '&#1083;&#1074;',
            self::LAK => '&#8365;',
            self::LBP => '&#163;',
            self::LKR => '&#8360;',
            self::LRD => '&#36;',
            self::LSL => '&#76;',
            self::LYD => '&#1604;.&#1583;',
            self::MAD => '&#1583;.&#1605;.',
            self::MDL => '&#76;',
            self::MGA => '&#65;&#114;',
            self::MKD => '&#1076;&#1077;&#1085;',
            self::MMK => '&#75;',
            self::MNT => '&#8366;',
            self::MOP => '&#77;&#79;&#80;&#36;',
            self::MUR => '&#8360;',
            self::MVR => '.&#1923;',
            self::MWK => '&#77;&#75;',
            self::MXN => '&#36;',
            self::MYR => '&#82;&#77;',
            self::MZN => '&#77;&#84;',
            self::NAD => '&#36;',
            self::NGN => '&#8358;',
            self::NIO => '&#67;&#36;',
            self::NOK => '&#107;&#114;',
            self::NPR => '&#8360;',
            self::NZD => '&#36;',
            self::OMR => '&#65020;',
            self::PAB => '&#66;&#47;&#46;',
            self::PEN => '&#83;&#47;&#46;',
            self::PGK => '&#75;',
            self::PHP => '&#8369;',
            self::PKR => '&#8360;',
            self::PLN => '&#122;&#322;',
            self::PYG => '&#71;&#115;',
            self::QAR => '&#65020;',
            self::RON => '&#108;&#101;&#105;',
            self::RSD => '&#1044;&#1080;&#1085;&#46;',
            self::RUB => '&#1088;&#1091;&#1073;',
            self::RWF => '&#1585;.&#1587;',
            self::SAR => '&#65020;',
            self::SBD => '&#36;',
            self::SCR => '&#8360;',
            self::SDG => '&#163;',
            self::SEK => '&#107;&#114;',
            self::SGD => '&#36;',
            self::SHP => '&#163;',
            self::SOS => '&#83;',
            self::SRD => '&#36;',
            self::SVC => '&#36;',
            self::SYP => '&#163;',
            self::SZL => '&#76;',
            self::THB => '&#3647;',
            self::TJS => '&#84;&#74;&#83;',
            self::TMT => '&#109;',
            self::TND => '&#1583;.&#1578;',
            self::TOP => '&#84;&#36;',
            self::TRY => '&#8356;', // New Turkey Lira (old symbol used)
            self::TTD => '&#36;',
            self::TWD => '&#78;&#84;&#36;',
            self::TZS => '',
            self::UAH => '&#8372;',
            self::UGX => '&#85;&#83;&#104;',
            self::USD => '&#36;',
            self::UYU => '&#36;&#85;',
            self::UZS => '&#1083;&#1074;',
            self::VND => '&#8363;',
            self::VUV => '&#86;&#84;',
            self::WST => '&#87;&#83;&#36;',
            self::XAF => '&#70;&#67;&#70;&#65;',
            self::XCD => '&#36;',
            self::XOF => '',
            self::XPF => '&#70;',
            self::ZAR => '&#82;',
            self::ZMW => '&#90;&#75;',
        });
    }
}
